INSERT INTO PIXEL(ROW, COLUMN, COLOR) VALUES (0, 0, '#000');
INSERT INTO PIXEL(ROW, COLUMN, COLOR) VALUES (1, 0, '#000');
INSERT INTO PIXEL(ROW, COLUMN, COLOR) VALUES (2, 0, '#000');
INSERT INTO PIXEL(ROW, COLUMN, COLOR) VALUES (3, 0, '#000');

INSERT INTO WALLET(TOKENS) VALUES (10);